# Ubuntu boilerplate stuff:
# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

if [ -f .localrc ]
then
	source .localrc
fi

export PS1="\[\033]0;\$TERMTITLE\007\]\[\033[00;31m\]\n\u@\h\[\033[00m\]\n\[\033[00;36m\]\$(__git_ps1 \"[%s] \")\w\[\033[00m\] > "

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

function hex {
 for num in $@
 do
  echo "obase=16;${num}" | bc
 done
}

function bin {
 for num in $@
 do
  echo "obase=2;${num}" | bc
 done
}

function dec {
 for num in $@
 do
  echo "ibase=16;obase=A;${num}" | bc
 done
}

function cal() { [[ -z $2 && $1 -le 12 && $1 -gt 0 ]] && command cal $1 $(date +%Y) || command cal $@; }

# Load RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
