#! /bin/bash

# Install process is pretty simple.  For each file in symlinks/, create a symlink in $HOME.
# Create a boilerplate .localrc (not symlinked.)  Skip any files that already exist.

function link_file {
    if [ -e $2 ]
    then
        echo "Unable to create $2, already exists."
    else
        ln -s $1 $2
		echo "Linked $1 to $2"
    fi

}

cd $HOME

DIR=$HOME/.dotfiles/symlinks
for src in $DIR/*.link
do
    dest=$HOME/.$(basename --suffix=.link $src)
	link_file $src $dest
done

LOCALRC=$HOME/.localrc
if [ -e $LOCALRC ]
then
    echo "Unable to create $LOCALRC, already exists"
else
    cat > $LOCALRC <<EOF 
# This file will be sourced before any bash scripts in your dotfile directory.
# Include any configuration specific to this machine, or anything you do not wish to add to 
# source control.
EOF
fi

if [ "$(uname -s)" == "Darwin" ]
then
    PROFILE=$HOME/.bash_profile
    if [ -e $PROFILE ]
    then
        echo "Unable to create $PROFILE, already exists"
    else
        cat > $PROFILE <<EOF
source .bashrc
EOF
    fi
fi
